### ISSUE TITLE
Portraits unable to be replaced

### ISSUE THREAD

**Issue by RottedFish** [everything8215/ff6tools#10]
<img width="608" alt="Screen Shot 2021-10-10 at 10 47 28 PM" src="https://user-images.githubusercontent.com/92285904/136730529-e49de355-8f64-42e9-b892-01afcd7e76bb.png">

Unable to replace Character portraits using the browser build. The palette hasn't been changed, so I'm not sure what's going on.

**Comment by everything8215** [comment]
Thanks for catching this. The portrait sprite sheet was missing the height and width. Fixed with https://github.com/everything8215/ff6tools/commit/8c233f0e51dd59bde3a0d02c6380b54bda50b723

**Comment by RottedFish** [comment]
hella
