### ISSUE TITLE
portrait hiccups

### ISSUE THREAD

**Issue by RottedFish** [everything8215/ff6tools#13]
I've been doing my best to try and port some portraits made for a mod for the Pixel Remaster of FF6, but this results in image cropping since the limit seems to be 40x40 pixels. You would assume this should end here, but I know for a fact such a port is possible, as I've seen it successfully operating in the SNES version of the game here:[
](https://twitter.com/stigma_male/status/1545211335801184256?s=20&t=AxbraDvHiWhkiL4m8pqxkg)

**Comment by everything8215** [comment]
Character portraits are limited to 40x40 pixels. Larger portraits are possible but would require an asm hack, which is outside the scope of ff6tools. Did you mean to include a link in your post? If you know of a hack with larger portraits, you might be able to ask the creators how they did it.

**Comment by RottedFish** [comment]
figured out how it was done. Source files were already 40x40, but I didn't have access to them. After some trial and error, I managed to get them running and looking good. I'll close this since it was basically a non-issue after all.
