### ISSUE TITLE
Non-english rom translation

### ISSUE THREAD

**Issue by shinra358** [everything8215/ff6tools#14]
when trying to edit the japan rom for ffvi, it is hard to do because it is in japanese. the pc version uses the japanese rom. can you translation the japanese text in the ui of your program?

**Comment by everything8215** [comment]
There's no actual Japanese text in the UI. FF6Tools pulls all of the Japanese text directly from your ROM. In order to change this you would need to translate the ROM itself. I don't know Japanese at all, so that's not something I can help with.

**Comment by shinra358** [comment]
if there is someone who knows how to have the program translate to what it
is pulling for ui usage only, thatll be great.

What will happen if the jpn verson was translated exactly like the english
version in a rom patch before loading it in ff6tools?

**Comment by everything8215** [comment]
I think I figured out a way to do this. I copied most of the text from the English GBA ROM into a new json file specifically for the Steam ROM, so the UI should mostly be in English now. Try loading up a fresh copy of the Steam ROM.

**Comment by shinra358** [comment]
Sweet, I'll check it out

**Comment by shinra358** [comment]
sweet. ui is in english. but edit boxes are in kanji still. if the kanji in
those boxes can have the same treatment but whatever we edit be in english
to us and auto converted back to kanji when we save it, thatll be cool

**Comment by shinra358** [comment]
steam saves it's rom as rom.bin.gz with rom.bin inside. The program saves
the rom as .gba when you save it. can you have the steam version be
converted back to rom.bin pls?

**Comment by everything8215** [comment]
The edit boxes contain the Japanese text data that is stored in the GBA ROM. As I understand, this text is never actually used in the Steam ROM so editing it will have no effect. You can change the "label" field to change what text is displayed in the UI, although you might need to re-open your ROM file for this to take effect. This won't affect the in-game text.

There might be other modding tools that can edit the in-game text for the Steam version, check the Steam forums.

After saving a ROM, you can simply change the filename to `rom.bin`.

**Comment by shinra358** [comment]
oh ok, its just when i do that, i think it gets corrupted. all i did was
drag an enemy downward a little and tried to save. Reloading then occupies all spaces in the enemy section with Guardx6

And when I drag that enemy down, I dont see any data change to the right about the vertical offset so im confused.

**Comment by shinra358** [comment]
i had to take it out of the zip first lol. it works. since it saves in zip, is there a possibilty that you can make it read inside of the zip archivers (.zip, .7z, .gz, etc)?

also, i realize that i do not see any of the doom spells and abilities in the ability list but i do see some unnamed entries like 10 entries or something like that. anybody got a chart that tells which of those unnamed entries are which?

**Comment by everything8215** [comment]
Sorry, you need to unzip your ROM file before you open it. FF6Tools saves a zip file so that it can download multiple files at once. Browsers often won't allow a website to do this otherwise.

I'm not sure what you mean by doom spells and abilities. Attack 13 is the Doom spell. Or are you talking about Doom the boss? Which unnamed entries are you referring to?

**Comment by shinra358** [comment]
there are other versions of it that target the whole party like the flying
eye boss in the dragons den. thanks for telling me that one. What about the
one that targets everyone? i think the boss name is plague

**Comment by everything8215** [comment]
It looks like attack 139 is a monster attack called Doom. That's the one that Plague uses. Plague is monster 386 btw.

**Comment by shinra358** [comment]
thank you very much!
