### ISSUE TITLE
Enhancement: Ability to add a new song for particular battles

### ISSUE THREAD

**Issue by shinra358** [everything8215/ff6tools#15]
Id like the ability to use custom songs for certain enemies

**Comment by everything8215** [comment]
You can choose the song that plays for each battle under Battle Properties. This has a dropdown with 8 choices, and the last two are unused. In the Japanese GBA ROM, you can change the last two songs by replacing the two bytes at 0xBA0AA with the songs that you want (use a hex editor). This might also work for the Steam version.

**Comment by shinra358** [comment]
I know, but from pre existing songs. I would like the ability to add new
entries if possible.

**Comment by everything8215** [comment]
I don't have any plans to add music modification functionality to FF6Tools. There are tools available for inserting custom music into the SNES ROM, check here: https://github.com/emberling. I don't think any such tools exist for the GBA version, though there is a nice patch which restores the SNES sounds: https://www.romhacking.net/hacks/657/. I don't think this would have any effect on the Steam version though. Maybe check here: https://steamcommunity.com/groups/ff-modding/discussions/10/451850213942999451/.
