### ISSUE TITLE
Steam Version EXE old ver

### ISSUE THREAD

**Issue by shinra358** [everything8215/ff6tools#16]
Is it possible to allow this program to read the exe of the old ver for steam and make similar modifications? It contains data that overwrites alot of things in the j rom it uses that can't be edited by just editing the j rom.

**Comment by everything8215** [comment]
No, sorry. What you're describing might be possible, but it's not something that I ever plan to add to FF6Tools. Modern executable files are very different from the ROM images from old game cartridges. FF6Tools is only meant to work with the SNES and GBA versions of FF6. It's just a coincidence that the Steam version happens to rip some game data from a slightly modified Japanese GBA ROM.

**Comment by shinra358** [comment]
oh ok, its just when i do that, i think it gets corrupted. all i did was
drag an enemy downward a little and tried to save.
