### ISSUE TITLE
Is there an applicable license for the project?

### ISSUE THREAD

**Issue by ghost** [everything8215/ff6tools#2]
About as simple as the title says... Is there an applicable license for this tool or is there none because of what it does? Asking in regards to forking and modding the tool on my own time. :)

Thanks!

**Comment by everything8215** [comment]
Good question. I hadn't even thought about a license. I guess I'll use GNU GPLv3. I'll add that next time I commit.

**Comment by ghost** [comment]
Good to know! Thank you for replying. :)
