### ISSUE TITLE
[Enhancement] Battle Character Slot X/Y Scale

### ISSUE THREAD

**Issue by shinra358** [everything8215/ff6tools#21]
Can you add the ability to adjust the scale of the character, weapons, and shields depending on the slot that the char is in (battle only)? I want to have the frontmost char with a bigger scale to the furthest char with a smaller scale. Possible?

**Comment by everything8215** [comment]
I think I've already answered this question in #17. If what you're asking for is possible, it would likely require an extensive asm hack and it's way beyond what FF6Tools is capable of.
