### ISSUE TITLE
Export/Import Game Title error

### ISSUE THREAD

**Issue by JordyVeldos** [everything8215/ff6tools#6]
Hello,

First of all, I am really fan of your work, but I do have a issue and I am almost sure it's because of my lack of knowledge, since I am new to editing ROMs.

When I load up the SNES FF3 (U) ROM it loads everything, but when I try to export the Graphics of Cinematic -> Title Screen: Game Title to a .PNG (I tried Indexed and RGB), edit it in photoshop and import the .PNG file again and try to save the ROM file, I get this question: "Some data has increased in size and no longer fits in its alotted range. What would you like to do?" 

I tried all the choices and none of them seemed to work, because after that I get this message: "Unable to save ROM. Try optimizing or expanding." I can still 'download' the ROM file, but when I try to open it in an emulator, it says it's corrupted.

Is there maybe a chance to make a simple tutorial of how to do this right or which programs to use? I would even pay you for that.

Thank you so much for your time and effort making this amazing web-based ROM editor and for reading my question

**Comment by everything8215** [comment]
Hi, thanks for the feedback. The "Game Title" graphics in the US version has this weird issue where the last tile only actually has enough pixel data for half a tile. This is why you see a little hole under the "s" when you open it in FF6Tools. This doesn't appear in-game though, and I'm not really sure why. When you import new graphics to replace it, FF6Tools can't deal with a half tile, so it expands it to a full tile, which then makes it too large to fit. That explains why you're getting an error message.

One thing you can can do to fix this is just to not load that half tile. If you have a .json file (you get one when you save a ROM with FF6Tools), you can open it and search for this line:

`"range": "0x8DE0-0x9EF0",`

and change `0x9EF0` to `0x9EE0`

I made this change to the default .json file, so it should now also work if you open a fresh ROM.

Some other tips:

- Make sure that the graphics you are importing doesn't have more tiles that the original
- If you have any unused tiles, make them blank to improve data compression (title/intro graphics data is compressed in the ROM)
- After editing a graphics image with an external program, save the image as an indexed png if possible. This is especially important if you want to match the color order of an existing palette

You also might be interested in this [tutorial](https://www.ff6hacking.com/wiki/doku.php?id=ff3:ff3us:tutorial:splashscreen). It's a little more advanced and makes use of a bunch of different tools, but it might be helpful.
