### ISSUE TITLE
Automatically changes to another event when scrolling to the bottom of one

### ISSUE THREAD

**Issue by VulpineAmethyst** [everything8215/ff6tools#8]
Whenever I try to scroll to the bottom of event 63 in FFVA, FF6Tools keeps switching me over to the dialogue entry for acquiring the Jobs in the Wind Shrine. I'm hoping to be able to identify the specific function which adds jobs so that I can implement a Four Job Fiesta run generator in [Exdeath](https://github.com/Aerdan/Exdeath), and this is getting in the way of finding out what that function is.

**Comment by everything8215** [comment]
Hi, thanks for the feedback. The event script editor for FF5 Advance is in pretty sad shape right now (at least compared to the SNES version). I'll try to get it fixed up soon, but in the mean time you might be able to use [this disassembly of the event script](https://www.mediafire.com/file/q9fonttstmrs0sj/ff5a_event_script.txt/file) to find what you're looking for.

The event command that gives jobs is 5B, so you can use a text editor and search the disassembly for ": 5B" to find where all the jobs are obtained. For example, the wind crystal jobs are at 083D/6060 in the North American version (0x3D6060 if you open the ROM in a text editor).

```
083D/6060: 5B 05              give job $05
083D/6062: 5B 06              give job $06
083D/6064: 5B 07              give job $07
083D/6066: 5B 0A              give job $0A
083D/6068: 5B 0D              give job $0D
083D/606A: 5B 0E              give job $0E
```

The job numbers for event command 5B are in sort of reversed 8-bit order compared to how they are listed in FF6Tools under Character/Job Names:

```
00: Ranger
01: Berserker
02: Samurai
03: Ninja
04: Dragoon
05: Thief
06: Monk
07: Knight
08: Beastmaster
09: Red Mage
0A: Blue Mage
0B: Summoner
0C: Time Mage
0D: Black Mage
0E: White Mage
0F: Mystic Knight
12: Freelancer
13: Mime
14: Dancer
15: Bard
16: Geomancer
17: Chemist
18: Gladiator
19: Cannoneer
1A: Oracle
1B: Necromancer
```

Let me know if that works for you. I'll post again here when I get the event script editor working a little better.

**Comment by VulpineAmethyst** [comment]
I ended up finding the info I needed from wormsofcan/x0_000, and have *mostly* managed to implement a four-job fiesta mode in [Exdeath](https://github.com/Aerdan/Exdeath). (I say 'mostly' because it currently breaks the game in at least two places.)
